---
title: "Lobster Exploration"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(here)
library(janitor)
```

## Task 2

```{r}
lobsters <- read_csv(here("data", "Lobster_Abundance_All_Years_20210412.csv"), na = c("-99999", "")) |> 
  clean_names() |> 
  uncount(count) # Gave each observation own row
```

Summary table

```{r}
lobs_sum <- lobsters |> 
  group_by(site, year) |> 
  summarize(number = n(),
            mean_length_mm = mean(size_mm))

ggplot(lobs_sum, aes(x = year, y = number)) +
  geom_point(aes(color = site))
```

Proportion of legal lobsters at each site for 2020\
legal lobster carapace length = 79.76 mm

```{r}
lobs_legal <- lobsters |> 
  filter(year == 2020) |> 
  mutate(legal = ifelse(size_mm > 79.76,
            "yes",
            "no")) |> 
  group_by(legal, site) |> 
  summarize(total = n())

ggplot(lobs_legal, aes(x = site, y = total)) +
  geom_col(aes(fill = legal), position = "fill")
```

## Task 4

Random Lobster Wrangling

```{r}
ex_a <- lobsters |> 
  filter(site %in% c("IVEE", "CARP", "NAPL"))

ex_b <- lobsters |> 
  filter(month == 8)

ex_c <- lobsters |> 
  filter(site == "AQUE" | size_mm > 70)

ex_d <- lobsters |> 
  filter(site != "NAPL")
unique(ex_d$site)
```

group_by

```{r}
ex_e <- lobsters |> 
  group_by(site) |> 
  summarize(cara_mean = mean(size_mm, na.rm = TRUE),
            cara_sc = sd(size_mm, na.rm = TRUE)
            )

ex_f <- lobsters |> 
  group_by(site, month) |> 
  summarize(max_cara = max(size_mm, na.rm = TRUE))
```

mutate()

```{r}
ex_g <- lobsters |> 
  mutate(size_cm = size_mm / 100)

ex_h <- lobsters |> 
  mutate(site = tolower(site))

ex_g <- lobsters |> 
  mutate(area = as.character(area))
```
